In [2]:
!pip install numpy pandas matplotlib seaborn scikit-learn

Collecting numpy
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
     ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
     --------------------------------------- 0.0/12.9 MB 660.6 kB/s eta 0:00:20
     --------------------------------------- 0.1/12.9 MB 880.9 kB/s eta 0:00:15
      --------------------------------------- 0.2/12.9 MB 1.8 MB/s eta 0:00:08
     - -------------------------------------- 0.4/12.9 MB 2.5 MB/s eta 0:00:06
     -- ------------------------------------- 0.7/12.9 MB 3.1 MB/s eta 0:00:05
     -- ------------------------------------- 0.9/12.9 MB 3.1 MB/s eta 0:00:04
     --- ------------------------------------ 1.1/12.9 MB 3.4 MB/s eta 0:00:04
     --- ------------------------------------ 1.1/12.9 MB 3.4 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.9 MB 3.7 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/12.9 MB 3.6 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/12.9 MB 3.1 MB/s eta 0:00:04
     ------ --------------------------------- 2.0/12.9 MB 3.4 MB/s eta 0:00:04
     ------ --------------------------------- 2.0/12.9 MB 3.5 MB/s eta 0:00:04
     ------ --------------------------------- 2.2/12.9 MB 3.3 MB/s eta 0:00:04
     ------- -------------------------------- 2.3/12.9 MB 3.2 MB/s eta 0:00:04
     ------- -------------------------------- 2.4/12.9 MB 3.1 MB/s eta 0:00:04
     ------- -------------------------------- 2.4/12.9 MB 3.1 MB/s eta 0:00:04
     ------- -------------------------------- 2.5/12.9 MB 3.0 MB/s eta 0:00:04
     ------- -------------------------------- 2.5/12.9 MB 2.8 MB/s eta 0:00:04
     -------- ------------------------------- 2.6/12.9 MB 2.8 MB/s eta 0:00:04
     -------- ------------------------------- 2.7/12.9 MB 2.7 MB/s eta 0:00:04
     -------- ------------------------------- 2.7/12.9 MB 2.7 MB/s eta 0:00:04
     -------- ------------------------------- 2.8/12.9 MB 2.6 MB/s eta 0:00:04
     -------- ------------------------------- 2.9/12.9 MB 2.5 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/12.9 MB 2.5 MB/s eta 0:00:05
     --------- ------------------------------ 3.0/12.9 MB 2.4 MB/s eta 0:00:05
     --------- ------------------------------ 3.0/12.9 MB 2.4 MB/s eta 0:00:05
     --------- ------------------------------ 3.1/12.9 MB 2.3 MB/s eta 0:00:05
     --------- ------------------------------ 3.1/12.9 MB 2.3 MB/s eta 0:00:05
     --------- ------------------------------ 3.2/12.9 MB 2.3 MB/s eta 0:00:05
     ---------- ----------------------------- 3.2/12.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.3/12.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.4/12.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.4/12.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.5/12.9 MB 2.1 MB/s eta 0:00:05
     ----------- ---------------------------- 3.6/12.9 MB 2.1 MB/s eta 0:00:05
     ----------- ---------------------------- 3.6/12.9 MB 2.1 MB/s eta 0:00:05
     ----------- ---------------------------- 3.7/12.9 MB 2.1 MB/s eta 0:00:05
     ----------- ---------------------------- 3.7/12.9 MB 2.0 MB/s eta 0:00:05
     ----------- ---------------------------- 3.8/12.9 MB 2.0 MB/s eta 0:00:05
     ----------- ---------------------------- 3.9/12.9 MB 2.0 MB/s eta 0:00:05
     ------------ --------------------------- 3.9/12.9 MB 2.0 MB/s eta 0:00:05
     ------------ --------------------------- 3.9/12.9 MB 2.0 MB/s eta 0:00:05
     ------------ --------------------------- 4.0/12.9 MB 1.9 MB/s eta 0:00:05
     ------------ --------------------------- 4.1/12.9 MB 1.9 MB/s eta 0:00:05
     ------------ --------------------------- 4.1/12.9 MB 1.9 MB/s eta 0:00:05
     ------------ --------------------------- 4.2/12.9 MB 1.9 MB/s eta 0:00:05
     ------------- -------------------------- 4.2/12.9 MB 1.9 MB/s eta 0:00:05
     ------------- -------------------------- 4.3/12.9 MB 1.9 MB/s eta 0:00:05
     ------------- -------------------------- 4.3/12.9 MB 1.9 MB/s eta 0:00:05
     ------------- -------------------------- 4.4/12.9 MB 1.8 MB/s eta 0:00:05
     ------------- -------------------------- 4.4/12.9 MB 1.8 MB/s eta 0:00:05
     ------------- -------------------------- 4.5/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.5/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.6/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.6/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.7/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.8/12.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.8/12.9 MB 1.8 MB/s eta 0:00:05
     --------------- ------------------------ 4.9/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.9/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 5.0/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 5.0/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 5.1/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 5.1/12.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 5.1/12.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.2/12.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.3/12.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.3/12.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.4/12.9 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 5.4/12.9 MB 1.7 MB/s eta 0:00:05
     ----------------- ---------------------- 5.5/12.9 MB 1.7 MB/s eta 0:00:05
     ----------------- ---------------------- 5.6/12.9 MB 1.7 MB/s eta 0:00:05
     ----------------- ---------------------- 5.7/12.9 MB 1.7 MB/s eta 0:00:05
     ----------------- ---------------------- 5.7/12.9 MB 1.7 MB/s eta 0:00:05
     ----------------- ---------------------- 5.7/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------ --------------------- 5.8/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------ --------------------- 5.9/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------ --------------------- 6.0/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------ --------------------- 6.0/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------ --------------------- 6.1/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------- -------------------- 6.2/12.9 MB 1.7 MB/s eta 0:00:05
     ------------------- -------------------- 6.3/12.9 MB 1.7 MB/s eta 0:00:04
     ------------------- -------------------- 6.3/12.9 MB 1.7 MB/s eta 0:00:04
     ------------------- -------------------- 6.4/12.9 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 6.5/12.9 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 6.6/12.9 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 6.6/12.9 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 6.7/12.9 MB 1.7 MB/s eta 0:00:04
     --------------------- ------------------ 6.8/12.9 MB 1.7 MB/s eta 0:00:04
     --------------------- ------------------ 6.9/12.9 MB 1.7 MB/s eta 0:00:04
     --------------------- ------------------ 7.0/12.9 MB 1.7 MB/s eta 0:00:04
     --------------------- ------------------ 7.0/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.2/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.3/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.3/12.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 7.4/12.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.5/12.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.6/12.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.6/12.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.7/12.9 MB 1.7 MB/s eta 0:00:04
     ------------------------ --------------- 7.8/12.9 MB 1.7 MB/s eta 0:00:04
     ------------------------ --------------- 7.9/12.9 MB 1.7 MB/s eta 0:00:04
     ------------------------ --------------- 8.0/12.9 MB 1.7 MB/s eta 0:00:03
     ------------------------ --------------- 8.0/12.9 MB 1.7 MB/s eta 0:00:03
     ------------------------- -------------- 8.1/12.9 MB 1.7 MB/s eta 0:00:03
     ------------------------- -------------- 8.2/12.9 MB 1.7 MB/s eta 0:00:03
     ------------------------- -------------- 8.3/12.9 MB 1.7 MB/s eta 0:00:03
     ------------------------- -------------- 8.4/12.9 MB 1.7 MB/s eta 0:00:03
     -------------------------- ------------- 8.4/12.9 MB 1.7 MB/s eta 0:00:03
     -------------------------- ------------- 8.6/12.9 MB 1.7 MB/s eta 0:00:03
     -------------------------- ------------- 8.6/12.9 MB 1.7 MB/s eta 0:00:03
     --------------------------- ------------ 8.7/12.9 MB 1.7 MB/s eta 0:00:03
     --------------------------- ------------ 8.8/12.9 MB 1.7 MB/s eta 0:00:03
     --------------------------- ------------ 8.9/12.9 MB 1.7 MB/s eta 0:00:03
     --------------------------- ------------ 9.0/12.9 MB 1.7 MB/s eta 0:00:03
     ---------------------------- ----------- 9.1/12.9 MB 1.7 MB/s eta 0:00:03
     ---------------------------- ----------- 9.2/12.9 MB 1.7 MB/s eta 0:00:03
     ---------------------------- ----------- 9.3/12.9 MB 1.7 MB/s eta 0:00:03
     ----------------------------- ---------- 9.4/12.9 MB 1.7 MB/s eta 0:00:03
     ----------------------------- ---------- 9.5/12.9 MB 1.7 MB/s eta 0:00:02
     ----------------------------- ---------- 9.5/12.9 MB 1.7 MB/s eta 0:00:02
     ----------------------------- ---------- 9.6/12.9 MB 1.7 MB/s eta 0:00:02
     ----------------------------- ---------- 9.7/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------ --------- 9.8/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------ --------- 9.9/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------ --------- 10.0/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------- -------- 10.1/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------- -------- 10.1/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------- -------- 10.2/12.9 MB 1.7 MB/s eta 0:00:02
     ------------------------------- -------- 10.3/12.9 MB 1.7 MB/s eta 0:00:02
     -------------------------------- ------- 10.4/12.9 MB 1.7 MB/s eta 0:00:02
     -------------------------------- ------- 10.4/12.9 MB 1.7 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.9 MB 1.7 MB/s eta 0:00:02
     -------------------------------- ------- 10.6/12.9 MB 1.7 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.9 MB 1.7 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.9 MB 1.7 MB/s eta 0:00:02
     --------------------------------- ------ 10.8/12.9 MB 1.7 MB/s eta 0:00:02
     --------------------------------- ------ 10.9/12.9 MB 1.7 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.9 MB 1.7 MB/s eta 0:00:02
     ---------------------------------- ----- 11.1/12.9 MB 1.7 MB/s eta 0:00:02
     ---------------------------------- ----- 11.1/12.9 MB 1.7 MB/s eta 0:00:02
     ---------------------------------- ----- 11.2/12.9 MB 1.7 MB/s eta 0:00:02
     ---------------------------------- ----- 11.3/12.9 MB 1.7 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.9 MB 1.6 MB/s eta 0:00:01
     ----------------------------------- ---- 11.4/12.9 MB 1.7 MB/s eta 0:00:01
     ----------------------------------- ---- 11.5/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.6/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.7/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 11.9/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------- -- 12.0/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------- -- 12.0/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------- -- 12.2/12.9 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.9 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.9 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.4/12.9 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.5/12.9 MB 1.6 MB/s eta 0:00:01
     -------------------------------------- - 12.6/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.7/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.9/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------  12.9/12.9 MB 1.6 MB/s eta 0:00:01
     ---------------------------------------- 12.9/12.9 MB 1.6 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     ---------------------------------------- 0.1/11.3 MB 2.3 MB/s eta 0:00:05
      --------------------------------------- 0.2/11.3 MB 2.0 MB/s eta 0:00:06
      --------------------------------------- 0.2/11.3 MB 1.9 MB/s eta 0:00:06
     - -------------------------------------- 0.3/11.3 MB 1.6 MB/s eta 0:00:07
     - -------------------------------------- 0.4/11.3 MB 1.6 MB/s eta 0:00:07
     - -------------------------------------- 0.4/11.3 MB 1.6 MB/s eta 0:00:07
     - -------------------------------------- 0.4/11.3 MB 1.6 MB/s eta 0:00:07
     - -------------------------------------- 0.5/11.3 MB 1.5 MB/s eta 0:00:08
     -- ------------------------------------- 0.6/11.3 MB 1.6 MB/s eta 0:00:07
     -- ------------------------------------- 0.6/11.3 MB 1.5 MB/s eta 0:00:08
     -- ------------------------------------- 0.7/11.3 MB 1.5 MB/s eta 0:00:08
     -- ------------------------------------- 0.8/11.3 MB 1.5 MB/s eta 0:00:08
     -- ------------------------------------- 0.8/11.3 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 0.9/11.3 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 0.9/11.3 MB 1.5 MB/s eta 0:00:07
     --- ------------------------------------ 1.0/11.3 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/11.3 MB 1.5 MB/s eta 0:00:07
     --- ------------------------------------ 1.1/11.3 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.1/11.3 MB 1.4 MB/s eta 0:00:08
     ---- ----------------------------------- 1.2/11.3 MB 1.4 MB/s eta 0:00:08
     ---- ----------------------------------- 1.2/11.3 MB 1.4 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/11.3 MB 1.4 MB/s eta 0:00:08
     ---- ----------------------------------- 1.4/11.3 MB 1.4 MB/s eta 0:00:08
     ----- ---------------------------------- 1.5/11.3 MB 1.4 MB/s eta 0:00:08
     ----- ---------------------------------- 1.5/11.3 MB 1.4 MB/s eta 0:00:08
     ----- ---------------------------------- 1.5/11.3 MB 1.4 MB/s eta 0:00:07
     ----- ---------------------------------- 1.6/11.3 MB 1.4 MB/s eta 0:00:07
     ----- ---------------------------------- 1.7/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.7/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.8/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.9/11.3 MB 1.4 MB/s eta 0:00:07
     ------ --------------------------------- 1.9/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.0/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.1/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.2/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.2/11.3 MB 1.4 MB/s eta 0:00:07
     ------- -------------------------------- 2.3/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.3/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.4/11.3 MB 1.4 MB/s eta 0:00:07
     -------- ------------------------------- 2.5/11.3 MB 1.5 MB/s eta 0:00:07
     -------- ------------------------------- 2.5/11.3 MB 1.5 MB/s eta 0:00:07
     --------- ------------------------------ 2.6/11.3 MB 1.5 MB/s eta 0:00:06
     --------- ------------------------------ 2.7/11.3 MB 1.5 MB/s eta 0:00:06
     --------- ------------------------------ 2.8/11.3 MB 1.5 MB/s eta 0:00:06
     ---------- ----------------------------- 2.8/11.3 MB 1.5 MB/s eta 0:00:06
     ---------- ----------------------------- 2.9/11.3 MB 1.5 MB/s eta 0:00:06
     ---------- ----------------------------- 3.0/11.3 MB 1.5 MB/s eta 0:00:06
     ---------- ----------------------------- 3.1/11.3 MB 1.5 MB/s eta 0:00:06
     ----------- ---------------------------- 3.2/11.3 MB 1.5 MB/s eta 0:00:06
     ----------- ---------------------------- 3.2/11.3 MB 1.5 MB/s eta 0:00:06
     ----------- ---------------------------- 3.3/11.3 MB 1.5 MB/s eta 0:00:06
     ----------- ---------------------------- 3.4/11.3 MB 1.5 MB/s eta 0:00:06
     ------------ --------------------------- 3.5/11.3 MB 1.6 MB/s eta 0:00:06
     ------------ --------------------------- 3.6/11.3 MB 1.6 MB/s eta 0:00:05
     ------------ --------------------------- 3.6/11.3 MB 1.6 MB/s eta 0:00:05
     ------------- -------------------------- 3.7/11.3 MB 1.6 MB/s eta 0:00:05
     ------------- -------------------------- 3.7/11.3 MB 1.6 MB/s eta 0:00:05
     ------------- -------------------------- 3.8/11.3 MB 1.6 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.0/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.0/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.1/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.2/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.2/11.3 MB 1.6 MB/s eta 0:00:05
     -------------- ------------------------- 4.2/11.3 MB 1.5 MB/s eta 0:00:05
     --------------- ------------------------ 4.3/11.3 MB 1.5 MB/s eta 0:00:05
     --------------- ------------------------ 4.3/11.3 MB 1.5 MB/s eta 0:00:05
     --------------- ------------------------ 4.4/11.3 MB 1.5 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.3 MB 1.5 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.5/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.6/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.7/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.7/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.8/11.3 MB 1.5 MB/s eta 0:00:05
     ---------------- ----------------------- 4.8/11.3 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 4.9/11.3 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 4.9/11.3 MB 1.5 MB/s eta 0:00:05
     ----------------- ---------------------- 5.0/11.3 MB 1.5 MB/s eta 0:00:05

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: C:\Users\Dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [8]:
df = pd.read_csv("../data/german_credit_data.csv")
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [14]:
df.describe()

        Unnamed: 0          Age          Job  Credit amount     Duration
count  1000.000000  1000.000000  1000.000000    1000.000000  1000.000000
mean    499.500000    35.546000     1.904000    3271.258000    20.903000
std     288.819436    11.375469     0.653614    2822.736876    12.058814
min       0.000000    19.000000     0.000000     250.000000     4.000000
25%     249.750000    27.000000     2.000000    1365.500000    12.000000
50%     499.500000    33.000000     2.000000    2319.500000    18.000000
75%     749.250000    42.000000     2.000000    3972.250000    24.000000
max     999.000000    75.000000     3.000000   18424.000000    72.000000

## Initial Observations

- Dataset contains customers mostly aged between 25–45
- Credit amount varies significantly (possible strong predictor)
- Loan duration ranges from short to long-term
- Job category indicates different employment levels

In [15]:
df.describe(include="object")

         Sex Housing Saving accounts Checking account Purpose  Risk
count   1000    1000             817              606    1000  1000
unique     2       3               4                3       8     2
top     male     own          little           little     car  good
freq     690     713             603              274     337   700

## Categorical Feature Insights

- Dataset is dominated by male customers
- Majority of customers own housing
- Significant missing values in checking accounts (~40%)
- Missing values treated as "unknown"
- Loan purpose varies across multiple categories
- Slight imbalance in target variable

In [12]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'Job', 'Housing', 'Saving accounts',
       'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk'],
      dtype='object')

In [16]:
df =df.drop("Unnamed: 0", axis=1)

In [18]:
df.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,49,male,1,own,little,NaN,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad